id = "dracula-by-gerson"
name = "Dracula by Gerson"
version = "0.5.0"
schema_version = 1
authors = ["Gerson Dantas"]
description = "Custom Dracula by Gerson"
repository = "https://github.com/GersonDantas/Custom-Dracula"
